"""""""""""""""""""""""""""""""""""""""
" GVIM dotfile
" Dylan Sarber
"
" Relies on plugins:
"   * pathogen
"   * vim-airline
"   * ctrlp
"   * tagbar
"""""""""""""""""""""""""""""""""""""""

"""""""""""""""""""""""""""""""""""""""
" Common Settings
"""""""""""""""""""""""""""""""""""""""
set guifont=Source\ Code\ Pro\ Light:h18
set linespace=4

