"""""""""""""""""""""""""""""""""""""""
" GVIM dotfile
" Dylan Sarber
"
" Relies on plugins:
"   * pathogen
"   * vim-airline
"   * ctrlp
"   * tagbar
"""""""""""""""""""""""""""""""""""""""

"""""""""""""""""""""""""""""""""""""""
" Common Settings
"""""""""""""""""""""""""""""""""""""""
set guifont=CamingoCode\ Regular:h14
"set background=light
colorscheme birds_of_paradise

