"""""""""""""""""""""""""""""""""""""""
" VIM dotfile
" 
" Author: Dylan Sarber
"""""""""""""""""""""""""""""""""""""""

"""""""""""""""""""""""""""""""""""""""
" Infect before everything else!
"""""""""""""""""""""""""""""""""""""""
execute pathogen#infect()

"""""""""""""""""""""""""""""""""""""""
" Common Settings
"""""""""""""""""""""""""""""""""""""""

" Default to 4 for spacing, although 2 is my preferred in most places...
set tabstop=4
set shiftwidth=4
set expandtab
set smartindent

" Goodies for working with source code
set hlsearch
set incsearch
set ignorecase
set smartcase
set number
syntax on

" To keep us sane when two tabs are side-by-side
set textwidth=79

" I'm not a fan of the window-opening defaults, open below and right
set splitbelow
set splitright

" For plugins
set laststatus=2

" These are just to ensure compatability
set encoding=utf-8
set t_Co=256
set bs=2

"set background=dark
colorscheme apprentice

" VIM swap files cause a lot of trouble inside directories
" They can go in a hidden dir in my home
set backupdir=$HOME/.vim-backup
set directory=$HOME/.vim-swaps

" Misc.
set showcmd

"""""""""""""""""""""""""""""""""""""""
" Mappings
"""""""""""""""""""""""""""""""""""""""

" Change leader to something easier to reach...
let mapleader = ";"

" Jump down/up while keeping line position
nmap j gj
nmap k gk

" Make some shortcuts for quicker buffer switching
nmap - :bp<CR>
nmap = :bn<CR>

" Shortcut for Bdelete script command
nnoremap <Leader>q :Bdelete<CR>

" Shortcut to EasyAlign variable assignments
vnoremap <Leader>a :EasyAlign<CR>*=<CR>

"""""""""""""""""""""""""""""""""""""""
" Plugins
"""""""""""""""""""""""""""""""""""""""

" Filetype
""""""""""
filetype plugin indent on

au filetype c setl shiftwidth=2
au filetype c setl tabstop=2
au filetype cpp setl shiftwidth=2
au filetype cpp setl tabstop=2

au filetype lua setl shiftwidth=2
au filetype lua setl tabstop=2

au filetype ruby setl shiftwidth=2
au filetype ruby setl tabstop=2

au filetype html setl shiftwidth=4
au filetype html setl tabstop=4

" VIM Airline
"""""""""""""
let g:airline_theme = 'luna'
let g:airline_left_sep='⟩'
let g:airline_right_sep='⟨'

" Enable airline's "tab" line at the top
let g:airline#extensions#tabline#enabled = 1

" Ctrl-P
""""""""
let g:ctrlp_map = '<c-p>'

" EasyAlign
"""""""""""
vnoremap <C-a> :EasyAlign =<cr>

