"""""""""""""""""""""""""""""""""""""""
" VIM dotfile
"
" Author: Dylan Sarber
"""""""""""""""""""""""""""""""""""""""

"""""""""""""""""""""""""""""""""""""""
" Infect before everything else!
"""""""""""""""""""""""""""""""""""""""
execute pathogen#infect()

"""""""""""""""""""""""""""""""""""""""
" Common Settings
"""""""""""""""""""""""""""""""""""""""

" Default to 4 for spacing, although 2 is my preferred in most places...
set tabstop=4
set shiftwidth=4
set expandtab
set smartindent

" Goodies for working with source code
set hlsearch
set incsearch
set ignorecase
set smartcase
set number
syntax on

" To keep us sane when two tabs are side-by-side
set textwidth=79

" I'm not a fan of the window-opening defaults, open below and right
set splitbelow
set splitright

" For plugins
set laststatus=2

" These are just to ensure compatability
set encoding=utf-8
set t_Co=256
set bs=2

colorscheme elflord

" Misc.
set showcmd

"""""""""""""""""""""""""""""""""""""""
" Mappings
"""""""""""""""""""""""""""""""""""""""

" Change leader to something easier to reach...
let mapleader = ";"

" Jump down/up while keeping line position
nmap j gj
nmap k gk

" Make some shortcuts for quicker buffer switching
nmap - :bp<CR>
nmap = :bn<CR>

" Single keystroke window movements
nnoremap <C-j> <C-W>j
nnoremap <C-k> <C-W>k
nnoremap <C-h> <C-W>h
nnoremap <C-l> <C-W>l

" Shortcut for Bdelete script command
nnoremap <Leader>q :Bdelete<CR>

" Shortcut to EasyAlign variable assignments
vnoremap <Leader>a :EasyAlign<CR>*=<CR>

"""""""""""""""""""""""""""""""""""""""
" Plugins
"""""""""""""""""""""""""""""""""""""""

" Filetype
""""""""""
filetype plugin indent on

au filetype c setl shiftwidth=2
au filetype c setl tabstop=2
au filetype cpp setl shiftwidth=2
au filetype cpp setl tabstop=2

au filetype lua setl shiftwidth=2
au filetype lua setl tabstop=2

au filetype ruby setl shiftwidth=2
au filetype ruby setl tabstop=2
au filetype eruby setl shiftwidth=2
au filetype eruby setl tabstop=2

au filetype html setl shiftwidth=2
au filetype html setl tabstop=2

au filetype go setl noexpandtab
au filetype go setl shiftwidth=4
au filetype go setl tabstop=4
